name: Deploy website

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          release: false
          llvm-version: 18

      - name: Set up Clay
        run: |
          set -euo pipefail

          mkdir -p _pkg/src

          git clone https://github.com/nicbarker/clay.git --depth=1 _pkg/src/clay
          cp -R _pkg/src/clay/bindings/odin/clay-odin _pkg/clay

      - name: Set up Dear ImGui
        run: |
          set -euo pipefail

          mkdir -p _pkg
          
          git clone https://gitlab.com/laytan/odin-imgui.git --depth=1 --branch=web-support _pkg/imgui

      - name: Create website
        run: |
          set -euo pipefail

          mkdir -p website/examples

          odin build examples/_build -out:build -debug

          examples=(
            "box2d-bunnies"
            "box2d-character"
            "bunny"
            "cbor"
            "clay-official-website"
            "hello"
            "imgui"
          )
          for example in "${examples[@]}"; do
            ./build "examples/$example" web -collection:pkg=_pkg -o:size -target-features:"simd128,bulk-memory"
            cp -R "examples/_out/$example/web" "website/examples/$example"
          done

          echo "Hellope!"        > website/index.html
          echo "nais.laytan.dev" > website/CNAME

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./website
      - uses: actions/deploy-pages@v4
        id: deployment
